name: Weather API with Hardcoded Key

on:
  push:
    branches:
      - main

jobs:
  weather-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set the API Key as an environment variable for debugging
      - name: Set API Key as environment variable
        run: |
          echo "MY_HCAPI_KEY=d6ee344647e407aa55ec488f464ac44b" >> $GITHUB_ENV

      - name: Expose API Key (Debugging)
        run: |
          echo "Exposing API Key: $MY_HCAPI_KEY"

      - name: Get weather data with hardcoded key
        run: |
          curl -X GET "https://api.openweathermap.org/data/2.5/weather?q=London&appid=$MY_HCAPI_KEY"
