name: Weather API with Hardcoded Key

on:
  push:
    branches:
      - main

jobs:
  weather-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get weather data with Secret key
        run: |
          curl -X GET "https://api.openweathermap.org/data/2.5/weather?q=London&appid=$MY_API_KEY"
